name: tbdex
description: Dart library for TBDex API.
version: 0.1.0
repository: https://github.com/TBD54566975/tbdex-dart

environment:
  sdk: ^3.1.4

dependencies:
  base32: ^2.1.3
  convert: ^3.1.1
  cryptography: ^2.7.0
  pointycastle: ^3.7.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
