name: web5
description: Dart library for Web5.
version: 0.1.0
repository: https://github.com/TBD54566975/web5-dart

environment:
  sdk: ^3.1.4

dependencies:
  collection: ^1.18.0
  convert: ^3.1.1
  cryptography: ^2.7.0
  pointycastle: ^3.7.3
  http: ^1.2.0
  base32: ^2.1.3

dev_dependencies:
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.21.0
